# Generated by Django 4.1.7 on 2023-03-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_rename_cotent_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
