# Generated by Django 4.1.7 on 2023-03-21 06:35

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=articles.models.articles_image_path
            ),
        ),
    ]
